export const queryKeys = {
  rooms: {
    all: ["rooms"],
    lists: () => [...queryKeys.rooms.all, "list"],
    list: (filters) => [...queryKeys.rooms.lists(), filters || {}],
    details: () => [...queryKeys.rooms.all, "detail"],
    detail: (id) => [...queryKeys.rooms.details(), id],
  },
  guests: {
    all: ["guests"],
    lists: () => [...queryKeys.guests.all, "list"],
    list: (status) => [...queryKeys.guests.lists(), status || "all"],
    details: () => [...queryKeys.guests.all, "detail"],
    detail: (id) => [...queryKeys.guests.details(), id],
  },
  hotels: {
    all: ["hotels"],
    lists: () => [...queryKeys.hotels.all, "list"],
    list: (filters) => [...queryKeys.hotels.lists(), filters || {}],
    me: () => [...queryKeys.hotels.all, "me"],
    aiosellRoomTypes: () => [...queryKeys.hotels.all, "aiosell-room-types"],
    details: () => [...queryKeys.hotels.all, "detail"],
    detail: (id) => [...queryKeys.hotels.details(), id],
    channelApprovals: (filters) => [
      ...queryKeys.hotels.all,
      "channel-approvals",
      filters || {},
    ],
    channelConfig: () => [...queryKeys.hotels.all, "channel-config"],
    liveRates: (params) => [
      ...queryKeys.hotels.all,
      "live-rates",
      params || {},
    ],
    liveInventory: (params) => [
      ...queryKeys.hotels.all,
      "live-inventory",
      params || {},
    ],
  },
  orders: {
    all: ["orders"],
    lists: () => [...queryKeys.orders.all, "list"],
    list: (filters) => [...queryKeys.orders.lists(), filters || {}],
    staff: () => [...queryKeys.orders.all, "staff"],
    foodItems: () => [...queryKeys.orders.all, "food-items"],
    details: () => [...queryKeys.orders.all, "detail"],
    detail: (id) => [...queryKeys.orders.details(), id],
  },
  requests: {
    all: ["service-requests"],
    lists: () => [...queryKeys.requests.all, "list"],
    list: (filters) => [...queryKeys.requests.lists(), filters || {}],
    staff: () => [...queryKeys.requests.all, "staff"],
    admin: () => [...queryKeys.requests.all, "admin"],
    details: () => [...queryKeys.requests.all, "detail"],
    detail: (id) => [...queryKeys.requests.details(), id],
  },
  dashboard: {
    all: ["dashboard"],
    stats: () => [...queryKeys.dashboard.all, "stats"],
    health: () => [...queryKeys.dashboard.all, "health"],
  },
  members: {
    all: ["members"],
    lists: () => [...queryKeys.members.all, "list"],
    list: (role) => [...queryKeys.members.lists(), role || "RECEPTIONIST"],
    details: () => [...queryKeys.members.all, "detail"],
    detail: (id) => [...queryKeys.members.details(), id],
  },
  ratePlans: {
    all: ["rate-plans"],
    lists: () => [...queryKeys.ratePlans.all, "list"],
    list: (filters) => [...queryKeys.ratePlans.lists(), filters || {}],
    details: () => [...queryKeys.ratePlans.all, "detail"],
    detail: (id) => [...queryKeys.ratePlans.details(), id],
    liveRates: (params) => [
      ...queryKeys.ratePlans.all,
      "live-rates",
      params || {},
    ],
  },
  roomTypes: {
    all: ["room-types"],
    lists: () => [...queryKeys.roomTypes.all, "list"],
    list: (filters) => [...queryKeys.roomTypes.lists(), filters || {}],
    details: () => [...queryKeys.roomTypes.all, "detail"],
    detail: (id) => [...queryKeys.roomTypes.details(), id],
  },
  subscriptions: {
    all: ["subscriptions"],
    lists: () => [...queryKeys.subscriptions.all, "list"],
    list: (filters) => [...queryKeys.subscriptions.lists(), filters || {}],
    details: () => [...queryKeys.subscriptions.all, "detail"],
    detail: (id) => [...queryKeys.subscriptions.details(), id],
  },
  transactions: {
    all: ["transactions"],
    lists: () => [...queryKeys.transactions.all, "list"],
    list: (params) => [...queryKeys.transactions.lists(), params || {}],
    details: () => [...queryKeys.transactions.all, "detail"],
    detail: (id) => [...queryKeys.transactions.details(), id],
  },
  invitations: {
    all: ["invitations"],
    lists: () => [...queryKeys.invitations.all, "list"],
    list: (hotelId) => [...queryKeys.invitations.lists(), hotelId || "all"],
    details: () => [...queryKeys.invitations.all, "detail"],
    detail: (id) => [...queryKeys.invitations.details(), id],
  },
};
